### ISSUE TITLE
How to extract poses and GT?

### ISSUE THREAD

**Issue by molu-ggg** [orhir/STG-NF#1]
you provide 'Data folder, including extracted poses and GT, can be downloaded using the [link](https://drive.google.com/file/d/1o9h3Kh6zovW4FIHpNBGnYIRSbGCu-qPt/view?usp=sharing).'
But the paper does not tell which model is used to  extract poses and GT, Can you tell me in detail ?

**Comment by orhir** [comment]
We used AlphaPose with Yolox-x detector for extracting keypoints and PoseFlow for tracking.

**Comment by ww1e** [comment]
Hi,I would like to try this model on other datasets, and i actually tried,but  it went wrong. Can you tell me in detail how to generate *_alphapose_tracked_person.json file ?

**Comment by orhir** [comment]
Sure.
We used AlphaPose with built-in pose tracking to get these files. 
You can then use our script to align to the required format.

**Comment by ww1e** [comment]
Thanks! I used the following command to get the pose file for HR-Avenue, is that right？
python gen_data.py --alphapose_dir ./data/HR-Avenue/testing/frames --dir ./data/HR-Avenue/testing/frames --outdir ./data/HR-Avenue/pose/test
And what is the different between the "outdir"file and "alphapose_dir"file?

**Comment by orhir** [comment]
The gen_data.py file runs the AlphaPose script for you.

Thus, the --alphapose_dir argument should refer to the AlphaPose directory.
If you already have the output of AlphaPose you can use the functions inside to parse it to the required format.
