### ISSUE TITLE
Avenue Dataset

### ISSUE THREAD

**Issue by molu-ggg** [orhir/STG-NF#10]
Hello, author. I'd like to inquire whether you have experimented with your excellent algorithm on the Avenue Dataset and how it performed. If you have tried it and the results were average, then I won't need to reproduce it.
Thank you !

**Comment by orhir** [comment]
We observed that the Avenue dataset labels are not entirely fair for pose-based solution, as most anomalies are either too fast or blurry for the pose detector (were not detected by our pose estimator), or very hard to be noticed without RGB context.
Thus we didn't think this dataset provides insights on our method and didn't further examine it.

**Comment by molu-ggg** [comment]
I see. Thank you for your answer.
