### ISSUE TITLE
How to run on a test video? 

### ISSUE THREAD

**Issue by mk8090** [orhir/STG-NF#11]

**Comment by orhir** [comment]
We provide details on how to run on both datasets.
If you want to run on a custom dataset - we currently don't support this feature, and may provide it in the future.

**Comment by mk8090** [comment]
thanks for the fast response. I just want to run on a single video and see the results.

**Comment by orhir** [comment]
So, as mentioned, we currently support the 2 evaluated dataset - you can see the README for further instructions.
For a single video, you may need to re-write some of our code.
Good luck!
