### ISSUE TITLE
The hyperparameter settings of YOLOX

### ISSUE THREAD

**Issue by JohhnyAngel** [orhir/STG-NF#14]
Thanks for your wonderful work! 
I understand that this work used AlphaPose with YOLOX detector for extracting keypoints and PoseFlow for tracking. But when I used the same method to preprocess the data, the number of people recorded in the final result was more than the JSON file you provided, such as ShanghaiTech's training set, and I processed more than 1000 people than your result. 
I preliminarily believe that the reason is the different hyperparameter settings of YOLOX. What are the two hyperparameters self.conf_thres and self.nms_thres in YOLOX that you set to (I used the default values of self.conf_thres = 0.1 and self.nms_thres = 0.6 in the alphapose code)? 
Thank you very much!

**Comment by orhir** [comment]
Thanks for showing interest in our work.

We didn't change any hyper-parameters and used the default for extracting poses.  
It is possible that AlphaPose updated its models or code.

To reconstruct our results we recommend using the provided data for the evaluated datasets.

**Comment by JohhnyAngel** [comment]
Thank you for your answer!
