### ISSUE TITLE
Pose extraction error

### ISSUE THREAD

**Issue by knbandit** [orhir/STG-NF#15]
Hello,

Thank you for your great work and for sharing the code.

I've been trying to replicate your experiment and figuring out how to use Alphapose with Yolox and PoseFlow to extract and track keypoints. 

While I got the code working for some videos, I came across a bug in `poseflow_infer.py` for video 03_0035 in the test set of ShanghaiTech dataset:

```
Traceback (most recent call last):
  File "/home/users/user1/miniconda3/envs/alphapose/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/users/user1/miniconda3/envs/alphapose/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/user1/research/experiments/AlphaPose/alphapose/utils/writer.py", line 167, in update
    poseflow_result = self.pose_flow_wrapper.step(orig_img, result)
  File "/home/users/user1/research/experiments/AlphaPose/trackers/PoseFlow/poseflow_infer.py", line 147, in step
    return self.final_result_by_name(frame_name)
  File "/home/users/user1/research/experiments/AlphaPose/trackers/PoseFlow/poseflow_infer.py", line 191, in final_result_by_name
    self.notrack[frame_name][pid]['idx'] = self.track[frame_name][pid+1]['new_pid']
IndexError: list index out of range
```

From `03_0035_alphapose_tracked_person.json` provided by you, it appears that you were able to extract and track keypoints for this video successfully. Did you come across this bug, and if so, how did you fix it? Any help would be awesome!

**Comment by orhir** [comment]
Thank you for showing interest in our work.

We did come across problems with the PoseFlow built-in tracker.

We don't have an absolute solution, as it turned out that some videos had different problems and bugs.
We suggest using another tracker for the problematic videos or debugging them for a quick patch.
Here is our edited code of poseflow_infer.py, we hope it can help you.

[poseflow_infer.zip](https://github.com/orhir/STG-NF/files/13598395/poseflow_infer.zip)

**Comment by knbandit** [comment]
Thank you for the edited code! I tried running it, and so far, it's working well for the ShanghaiTech dataset. Regarding using another tracker, did you try a different one, and was it better in terms of speed and performance?

**Comment by orhir** [comment]
We also tried the default Re-ID tracker provided by AlphaPose.
Regarding speed, the Re-ID track is far superior, but we noticed a slight reduction in the tracking quality compared to PoseFlow.
So from our experience, if you want a fast tracker - the Re-ID model is the better option, but if you care more about accuracy the PoseFlow is superior.
