### ISSUE TITLE
About RBDC and TBDC

### ISSUE THREAD

**Issue by ythee2001** [orhir/STG-NF#19]
Hi, Thank you for your great work.

I want to know about how to get the result of RBDC and TBDC metrics.

Best,

**Comment by orhir** [comment]
Hi, thank you.
We based the RBDC and TBDC calculation on the following repo:
https://github.com/lilygeorgescu/AED/tree/master/evaluation

**Comment by ythee2001** [comment]
Thank you for your answer. 
Could you tell me where I should get the txt files needed for **tracks-path** and **anomalies-path** in the file that the metrics are calculated?

**Comment by ythee2001** [comment]
Thank you for your great work.

I have got all tracks txt files, but I don't know how to get the anomalies txt file.

Best,

**Comment by orhir** [comment]
Hi, sorry for the late response.
We extracted these information from the dataset GT files. 
I will check if we can upload these files.

**Comment by ythee2001** [comment]
Thanks!

I notice that the GT files downloaded through [https://drive.google.com/file/d/1o9h3Kh6zovW4FIHpNBGnYIRSbGCu-qPt/view?usp=sharing](url) are different from the files in [https://github.com/orhir/STG-NF/tree/main/data/UBnormal/gt](url) . 

The files in [https://github.com/orhir/STG-NF/tree/main/data/UBnormal/gt](url) have some that can be opened and these are in utf-8 encoded format. The files in [https://drive.google.com/file/d/1o9h3Kh6zovW4FIHpNBGnYIRSbGCu-qPt/view?usp=sharing](url) doesn't have these files, they are all in ANSI format and show garbled code. 

Can you please tell me the reason for this and which is correct?

I try to run the file that computes RBDC and TBDC. As far as I know,  it needs that all GT files should be utf-8 encoded format.

And what do the two numbers at the end of this GT file represent?
![批注 2024-05-13 111800](https://github.com/orhir/STG-NF/assets/165020224/df4413e6-f2da-4a86-a92d-b3148a06e1e6)


Best!

**Comment by orhir** [comment]
Hi, these files were reformatted for our internal code.
I'm attaching the txt files for both datasets, let me know if you need anything else.

The UBnorm
al GT can be extracted using the official repo script:
https://github.com/lilygeorgescu/UBnormal

[metrics.zip](https://github.com/orhir/STG-NF/files/15309342/metrics.zip)

**Comment by ythee2001** [comment]
Thanks!

I have extracted UBnormal GT a few days ago. But I have an another question. I want to extract the abnomal gt txt files on both datasets. I'm looking forward to your attach.

And as far as I know, there are five parameters in the gt txt file if I try to calculate RBDC and TBDC.

Best!

**Comment by orhir** [comment]
The attached file is in the previous comment, please let us know if this helps

**Comment by ythee2001** [comment]
Thanks!

I can run the code that computes RBDC and TBDC, but both show 0.

The frame number I set are 24 and 16 on ST and UB datasets as you mentioned in paper.

Best!

**Comment by orhir** [comment]
Hi, not sure what you mean by setting the frame numbers.
In order to calculate these metrics, one needs to get the anomaly scores and according to the skeleton coordinates calculate the bounding boxes according to the required format. These should all be set in the metric file provided.

**Comment by ythee2001** [comment]
Hi!

The picture is as follows. I want to know if the metric **num-frames** should be the same with the paper mentioned.

![批注 2024-05-15 215623](https://github.com/orhir/STG-NF/assets/165020224/584931cc-ad8c-4e54-9795-ffb06c44cf4b)


Best!

**Comment by orhir** [comment]
Please note that here "num-frames" is the total number of frames in the videos (according to the official repo).
The parameter mentioned in the paper is the size of the sliding window used to evaluate the anomaly score.

**Comment by ythee2001** [comment]
Thank you for your great work and detailed answers!
Best!

**Comment by UyNa1t** [comment]
@ythee2001 Hello, now I also want to get the GT text file of the UBnornal data set through the  official repo script:
https://github.com/lilygeorgescu/UBnormal, but I'm having some problems. I want to know what the base_input_folder and abnormal_video_names_path or normal_video_names_path in the figure are and how to obtain them
![Image](https://github.com/user-attachments/assets/be9d49f6-1940-431f-951d-6a12ed79d169)
In addition, I would like to know why the num-frames parameters of the two data sets should be set respectively during the computation
Best!

**Comment by dingjianglian** [comment]
> Thank you for your great work and detailed answers!感谢您的出色工作和详细的回答！ Best!  最好！

Hi, Thank you for your great question. 
I want to get the result of RBDC and TBDC metrics but I was failed.
If you do it successfully, can you send me the code by email(18752903988@163.com)
Best!
