### ISSUE TITLE
Coding problems

### ISSUE THREAD

**Issue by molu-ggg** [orhir/STG-NF#2]
Hello ,Author , I meet some coding problems .
In 'dataset.py' ，about 63 lines ` ab_labels = get_ab_labels(self.segs_data_np_ab, self.segs_meta_ab, self.seg_len,)`  self.seg_len is Interger ,but in pose_until.py `def get_ab_labels(global_data_np_ab, segs_meta_ab, segs_root=None):` ,segs_root is a path ,so how can I deal with it ?

**Comment by orhir** [comment]
Hi, Thanks.
Repo updated and fixed.
