### ISSUE TITLE
Why does the logdet remain unchanged after ST-GCN

### ISSUE THREAD

**Issue by zz1565** [orhir/STG-NF#20]
![屏幕截图 2024-05-15 154311](https://github.com/orhir/STG-NF/assets/149766748/df659df7-e9ba-4abe-9dcf-89931edb52ee)

Thank you for your outstanding work. I'm a bit curious after reading the code. Why wasn't the logdet parameter passed in in ST-GCN? If I change the ST-GCN module to another module, is h calculated directly and then the scale calculated? So is logdet only related to the calculated h in the affine coupling layer?

**Comment by orhir** [comment]
Thanks you for showing interest in our work.

As NF needs to be bijective, and deep neural networks aren't, this special architecture makes sure that the logdet of the affine coupling depends on the result of the ST-GCN and not its parameters.

You can further read on the logdet of the different components in the following article, which we cite in our work:
https://arxiv.org/pdf/1807.03039

**Comment by zz1565** [comment]
Thank you very much for your answer. Now I have replaced the ST-GCN module with another module, but the loss has become negative. What is the reason and how should I solve it? Thank you again

**Comment by orhir** [comment]
Please note that the loss is the negative log likelihood which is minimized. Thus, it can be negative.

**Comment by zz1565** [comment]
Okay, I understand. Thank you very much!
