### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by zz1565** [orhir/STG-NF#22]
Thank you for your outstanding work！ May I ask whether the key points with low confidence were removed during data preprocessing?

**Comment by orhir** [comment]
We support this pre-processing feature in a parameter called 'train_seg_conf_th'.
However, in our work the default value is 0, thus no thresholding is done.

**Comment by zz1565** [comment]
Thank you for your answer. Is there any problem such as occlusion in the input skeleton coordinates? Can the model of the normalized flow be modified accordingly for this problem?

**Comment by orhir** [comment]
Our model relies on tracked pose sequences.
It showed good performance when dealing with noisy data, however, there are no design modifications for occlusions.
