### ISSUE TITLE
What are the "category_id" in the dataset used for?

### ISSUE THREAD

**Issue by TheExileCoder** [orhir/STG-NF#23]
![image](https://github.com/orhir/STG-NF/assets/61927003/1fe99bd1-0575-415d-9191-fa8c8e8c3749)

like the image, it comes from shanghaitech dataset and in pose/train/01_0014_alphapose-results.json

does your method use category information, I didn't found its usage.

thanks!

**Comment by orhir** [comment]
This output is from the pose estimator (AlphaPose). I don’t think we use this field.

**Comment by TheExileCoder** [comment]
ok, thanks!
