### ISSUE TITLE
gmm prior

### ISSUE THREAD

**Issue by akidway** [orhir/STG-NF#24]
Hi, Thank you for your great work.

In your [code](https://github.com/orhir/STG-NF/blob/edb5f3220332e160e4d20ce258787d5e2d7e0200/models/STG_NF/model_pose.py#L385), means and logs are given for supervised training. 
For gmm model, usually there is a weight for each gaussian distribution. But I can't find the weight in your code.
Could you please point out this part of the code?

And what is [model_confidence](https://github.com/orhir/STG-NF/blob/edb5f3220332e160e4d20ce258787d5e2d7e0200/models/training.py#L128) in your code, is that gmm weight?

**Comment by orhir** [comment]
Hi,
1. We don't use GMM weights. In the supervised setting, we know exactly which sample belongs to which Gaussian, thus we maximize the probability of that sample given the mean. Please refer to our paper for further details.
2. Model confidence isn't used in the vanilla version of our model. It is a feature that lets you weigh samples according to the Pose Estimation confidence score.
