### ISSUE TITLE
About generating custom dataset.

### ISSUE THREAD

**Issue by kkIIun** [orhir/STG-NF#25]
Hi,

Thank you for your great work.

I'm trying to generate a custom dataset using gen_data.py, but the results for UBnormal and Shanghaitech are not the same. I have followed all your guidance completely.

If there are any other settings (e.g., conf_thre, nms_thre, etc.) that I need to adjust, please let me know.

Thank you!

**Comment by orhir** [comment]
Thank you for showing interest in our work.
For ShanghaiTech we used the skeletons provided by [Graph Embedded Pose Clustering for Anomaly Detection](https://github.com/amirmk89/gepc).
For UBnormal, we extract skeletons using the default parameters of AlphaPose, using YOLO-X detector.

**Comment by ythe2001** [comment]
> Thank you for showing interest in our work. For ShanghaiTech we used the skeletons provided by [Graph Embedded Pose Clustering for Anomaly Detection](https://github.com/amirmk89/gepc). For UBnormal, we extract skeletons using the default parameters of AlphaPose, using YOLO-X detector.

For UBnormal, the pose is extracted by AlphaPose and YOLO-X detector. How about gt? How are the files in gt extracted?

**Comment by orhir** [comment]
Using the GT file from the dataset, we locate using IDs and locations the normal and abnormal poses.

**Comment by ythe2001** [comment]
If I want to use it on other datasets, how should the GT file be extracted?

**Comment by orhir** [comment]
It depends on your dataset.
If you have a pose-based dataset - it's straightforward.
If it is segmentation based (like UBnormal) - then you should extract what poses are normal/abnormal according to the keypoints locations.
