### ISSUE TITLE
Supervised Training on UBnormal Dataset

### ISSUE THREAD

**Issue by Gigi-Al** [orhir/STG-NF#27]
Hello,

Thank you for the great work and repository! I have a question regarding the UBnormal dataset. In the supervised setting, the training set is highly imbalanced, with far fewer abnormal scenarios (roughly 40 times fewer than normal). How did you address this imbalance? Did you use any data augmentation or weighted loss? Were the limited abnormal samples sufficient for training the encoder to map them correctly in the latent space?

Thanks again for your efforts!

**Comment by orhir** [comment]
Imbalanced datasets are very common for anomaly detection, as abnormal events are hard to collect.
We didn't use any special data augmentations or weighted loss.

Our supervised method builds upon the unsupervised setting, ensuring known abnormal samples get low probabilities.
This is done by explicitly mapping the known abnormal samples to a Gaussian which is "far" from the Gaussian of normal samples.
The full explanation is in our paper.

**Comment by Gigi-Al** [comment]
Thank you for sharing the information.
