### ISSUE TITLE
Hi orhir I tried to contact you via your email, but it does not available. Thats why i tring to contact you from here. 

### ISSUE THREAD

**Issue by Chathura-Ranasinghe** [orhir/STG-NF#28]
I would appreciate your help with implementing this project. I'm having trouble reproducing the real-time testing outputs you provided on the https://orhir.github.io/STG_NF/ site. I've tried to implement it myself but without success. Could you please help me with the implementation process like you did? Please guide me on this. 

Thank you

**Comment by orhir** [comment]
We provide detailed instructions on how to run our model on both datasets.
Could you please be more specific regarding your request?
Are you referring to the visualizations?

**Comment by Chathura-Ranasinghe** [comment]
Thank you for your response. 

Yes, It's about the visualizations. The instructions you provided are crystal clear. I trained and evaluated it on your exciting dataset, and everything worked fine. However, I encountered a problem when trying to test it on video footage and obtain the output with alphapose as shown on the website. I went through your code but couldn't find a way to do it.  Kindly hope your help  and instructions on it.

**Comment by orhir** [comment]
Please take a look at our response in issue #4.
We don't provide visualization tools; however, in the response mentioned, we give a brief outline of how it was done.

**Comment by Chathura-Ranasinghe** [comment]
Thanks for you quick response. I read it and understood and made it clear with my one question. But, I am still unable to use this model to evaluate custom videos. 

I use this command to get the correct output. 
python train_eval.py --vid_path_test 02.avi  --checkpoint checkpoints/ShanghaiTech_85_9.tar  

Can you tell me what am I did wrong here?

**Comment by orhir** [comment]
Our code doesn't support custom datasets out of the box.
This shouldn't be too complicated, by should require some code adjustments.

You might need to adjust the dataloader a bit to make sure all formats are compatible.
Moreover, you might need to make sure the code doesn't require GT annotations, in case you don't have them.

**Comment by Chathura-Ranasinghe** [comment]
Noted. I'd start working on it. I appreciate your help and this great project. Thank you so much.

**Comment by UyNa1t** [comment]
@Chathura-Ranasinghe 
Hello, 
may I ask if you have completed the real-time visualization content on the https://orhir.github.io/STG_NF/ site? If you have successfully achieved it, could you please advise me on how to proceed?
Looking forward to your reply
