### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by Chathura-Ranasinghe** [orhir/STG-NF#29]

**Comment by Chathura-Ranasinghe** [comment]
Hi Orhir,

Thank you for your previous guidance in resolving the issue I encountered in your project. Following your instructions, I began to modify your work to test it on a custom test video. However, I encountered an issue with visualization when setting up alphapose. I wanted to ask if you used PyTorch3D for visualization or if you used any alternative method.

Highly appreciate your help

**Comment by orhir** [comment]
Hi, we didn't use any complicated visualization methods, just Matplotlib and OpenCV.
After matching the model scores to the human bounding boxes - we just added the text on top of the image.

**Comment by 18767953136** [comment]
Could you please provide the visualization code? Thank you very much.

**Comment by orhir** [comment]
Please take a look at our response in issue #28 and #4.
We don't provide visualization tools; however, in the response mentioned, we give a brief outline of how it was done.
