### ISSUE TITLE
UBNormal supervised and unsupervised training

### ISSUE THREAD

**Issue by molu-ggg** [orhir/STG-NF#3]
Hello, according to your readme document, I can know the command of unsupervised training, but I do not know what command UBnormmal executes to perform supervised training ?

**Comment by orhir** [comment]
Hi,
All you need is to run the training script with --pose_path_train_abnormal flag and specify the abnormal pose's path.
Please note that UBnormal's pixel-level annotations must be available for this function to work.

Good luck.
