### ISSUE TITLE
How to get the “gt” subfloder of each dataset

### ISSUE THREAD

**Issue by 1972127866** [orhir/STG-NF#30]
I'm curious about how the contents of the "gt" subfolder in each dataset of your collection are obtained. Could you please share the detailed process you followed? I would like to apply the model you have proposed to other datasets and improve it.
![image](https://github.com/user-attachments/assets/143df076-03c4-401e-b01c-c49ae705a290)

**Comment by orhir** [comment]
Hi,
We provide a dataset link, including GT annotations in the README file.
In addition, we also describe using custom datasets.
Good luck.
