### ISSUE TITLE
Questions about the UBnormal dataset

### ISSUE THREAD

**Issue by WJL-prog** [orhir/STG-NF#31]
Thank you very much for your work! I would like to ask, after downloading the data folder, I noticed that in the UBnormal dataset there are only 'gt' and 'pose' folders, but no 'videos'. Could you please let me know where I can get the videos? Thank you very much for your help and response!
![Uploading 屏幕截图 2024-12-24 100610.png…]()

**Comment by orhir** [comment]
Our network works on pose sequences, and as such, it doesn't require the original video data for processing. 
The pose sequences of the UBnormal dataset were extracted from the original videos, which you can find in the official UBnormal dataset repository.

If you need the video data, I recommend visiting the official dataset page to download it directly from there.

**Comment by WJL-prog** [comment]
Thank you very much for your reply and assistance! This will greatly facilitate my upcoming work.
