### ISSUE TITLE
About Log-likelihood Score

### ISSUE THREAD

**Issue by sasakits** [orhir/STG-NF#4]
Hi, Thank you for your great work.

I want to know about how to get the result of Log-likelihood Score.
I would like to output it frame by frame as shown in your Figure 5. Log-likelihood Score Examples.

Best,

**Comment by orhir** [comment]
Hi,

Do you refer to the likelihood graph as a function of time or the video with scores plot?
The function get_dataset_scores() in scoring_utils.py returns the scores list. You can use this list to plot graphs, as in Figure 5.

Regarding the other plot, we currently don't support plotting the output videos with scores, but might add it in the future.
This was done using the metadata list to link each score to the pose in time.

Hopes this clarifies things.
