### ISSUE TITLE
Prior Distribution Selection

### ISSUE THREAD

**Issue by Gigi-Al** [orhir/STG-NF#5]
Hello,

Thanks for this great work. I have read your paper but I could not find details of the chosen normal distribution for the Unsupervised Experiment on the ShanghaiTech Anomaly Dataset. Can you tell me what is the mean vector and the covariance matrix for this experiment?

Thanks!

**Comment by orhir** [comment]
Sure, this is done using the parameter R.
For the unsupervised setting, we used N(3, I), and for the supervised, we used N(10, I).

We will add these details to an updated version of the paper.

**Comment by Gigi-Al** [comment]
Thanks!
