### ISSUE TITLE
ShangHaiTech Campus AUC Result Unclear

### ISSUE THREAD

**Issue by XiaolanPan** [orhir/STG-NF#6]
Thank you for providing the paper and related code implementation. While reading the paper, I did not find a clear indication of whether the AUC results in ShangHaiTech are supervised or unsupervised. This is because in the comparison table of the methods you provided, I observed that some are weakly supervised. Could you please confirm whether the AUC results in ShangHaiTech are unsupervised? Thank you very much.

**Comment by orhir** [comment]
Hi,
The AUC for ShaghaiTech is indeed unsupervised.
The supervised method evaluated on UBnormal dataset only.
