### ISSUE TITLE
About how to save and visualize the results

### ISSUE THREAD

**Issue by harveyzoka** [orhir/STG-NF#7]
Hi, 

Thank you for your excellent work.

Can you guide me on how to visualize the result of video combination pose, log-likehood plot like how you show the result on https://orhir.github.io/STG_NF/?
Thanks you so much,

Best regards,

**Comment by orhir** [comment]
Hi, 
Please refer to issue #4 .
In short, we currently don't support it in the public repository, and might add it in the future.

**Comment by harveyzoka** [comment]
Hi,

Thanks for kindly response!

Sorry about my request, I just started learning about computer vision (anomaly detection). I have written the log-likelihood Score plots. Could you share the scripts by email? I just want to learn more about how you visualize it really impressive.

However, if cannot, I'm looking forward to you adding it in the future.

Best regards,

**Comment by orhir** [comment]
We will do our best to share this script in the future.
In a nutshell, as you have  the normality score for each person in each frame, you can plot it next to it using OpenCV or other python editing package.
