### ISSUE TITLE
May I ask where to download the dataset？

### ISSUE THREAD

**Issue by wfdsll** [orhir/STG-NF#9]
May I ask where to download the dataset？

**Comment by orhir** [comment]
Sure.
The datasets can be downloaded from their official repos and are publicly available.
In addition, we provide the extracted pose sequences used for both datasets. The link is in the README file.

**Comment by wfdsll** [comment]
May I ask if your code is a video or an image as input


May I ask if your code is a video or an image as input

王福丹
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "orhir/STG-NF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 下午3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [orhir/STG-NF] May I ask where to download the dataset？ (Issue #9)





 
Sure.
 The datasets can be downloaded from their official repos and are publicly available.
 In addition, we provide the extracted pose sequences used for both datasets. The link is in the README file.

**Comment by orhir** [comment]
Our method works on human pose sequences extracted from videos.
Details about the method can be found in our paper.

**Comment by wfdsll** [comment]
Thank you for your reply.I am very interested in your paper. May I ask if there are any innovations that can be made on it?




王福丹
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "orhir/STG-NF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 中午12:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [orhir/STG-NF] May I ask where to download the dataset？ (Issue #9)





 
Our method works on human pose sequences extracted from videos.
 Details about the method can be found in our paper.

**Comment by orhir** [comment]
Thanks for the interest.
Of course, there are plenty of possible future works that can be made.

**Comment by wfdsll** [comment]
Hello, the test set of the shanghaitech dataset has been downloaded with processed images. How can I extract the bones to obtain the. json file?


王福丹
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "orhir/STG-NF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月6日(星期四) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [orhir/STG-NF] May I ask where to download the dataset？ (Issue #9)





 
Thanks for the interest.
 Of course, there are plenty of possible future works that can be made.

**Comment by orhir** [comment]
The extracted pose files are available for download - link in the README file.
We used AlphaPose and PoseFlow to extract the pose sequences, and provided a python file to convert to our required format.
Please read carefully the paper for implementation details, and the README file for all required information.

**Comment by wfdsll** [comment]
Hello，May I ask"01_0014_alphapose_tracked_person.json" and "01_0014_alphapose-results.json"What is the difference between these two files.


王福丹
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "orhir/STG-NF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月9日(星期天) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [orhir/STG-NF] May I ask where to download the dataset？ (Issue #9)





 
The extracted pose files are available for download - link in the README file.
 We used AlphaPose and PoseFlow to extract the pose sequences, and provided a python file to convert to our required format.
 Please read carefully the paper for implementation details, and the README file for all required information.

**Comment by orhir** [comment]
Our method uses a slightly different format than AlphaPose format's, thus we provide the conversion code.
I am closing this issue, as the original question has been answered.
In case you have a new issue you are welcome to open a new issue.

**Comment by wfdsll** [comment]
王福丹
***@***.***



&nbsp;Hello, can you share the anomaly visualization score code in the article




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "orhir/STG-NF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月16日(星期天) 晚上6:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [orhir/STG-NF] May I ask where to download the dataset？ (Issue #9)





 
Closed #9 as completed.

**Comment by orhir** [comment]
Hi,

The visualization code is based on a debug version of our code which is not
fully compatible with the version on GitHub.
We may implement the visualization of the published code in the future.
